### ISSUE TITLE
Runnig ocis-hello from example guide broken

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis-hello#117]
Following the guide leads to a `The resource from “https://localhost:9200/hello.js” was blocked due to MIME type (“text/plain”) mismatch` error for `hello.js` in the console. Perhaps needs to be fixed within `ocis-pkg/middleware/static.go`

**Comment by wkloucek** [comment]
@pascalwengerter mimetype looks good on my side

![image](https://user-images.githubusercontent.com/34452982/131320102-b7003163-7f1f-481e-9d33-fb4d29feacb0.png)

@gmgigi96 which browser do you use? are there other error messages (eg. a response code 404, which would be then also plain text)?

**Comment by pascalwengerter** [comment]
> @pascalwengerter mimetype looks good on my side
> 
> ![image](https://user-images.githubusercontent.com/34452982/131320102-b7003163-7f1f-481e-9d33-fb4d29feacb0.png)
> 
> @gmgigi96 which browser do you use? are there other error messages (eg. a response code 404, which would be then also plain text)?

I tried it in both Firefox and Chrome and it didn't work. Also pulled @fschade in at some point and he ran into the same issue - maybe updating the dependencies (e.g. chi-router foo) fixed some stuff? 🤔

**Comment by wkloucek** [comment]
> I tried it in both Firefox and Chrome and it didn't work. Also pulled @fschade in at some point and he ran into the same issue - maybe updating the dependencies (e.g. chi-router foo) fixed some stuff?

I also couldn't reproduce this before the dependency bump. Maybe we can check together on your setup?
