### ISSUE TITLE
Adjust for Phoenix 0.2.6 + solve potential issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-hello#39]
- [x] REQUIRES: update ocis-phoenix https://github.com/owncloud/ocis-phoenix/issues/22
- [ ] test that the app still works

It is possible that latest changes to the way the top bar and navigation works might break some things in ocis-hello.

**Comment by tboerger** [comment]
There is no breaking change part of the changelog :(

**Comment by PVince81** [comment]
I think @LukasHirt is already on it

**Comment by LukasHirt** [comment]
With 0.2.6 it won't work because of an error related to store. Fixed in https://github.com/owncloud/phoenix/pull/2837 but wasn't part of the release.

**Comment by LukasHirt** [comment]
> With 0.2.6 it won't work because of an error related to store. Fixed in owncloud/phoenix#2837 but wasn't part of the release.

With 0.2.7-alpha1 release was the issue solved. ocis-hello now works fine.
